version: '3.7'

services:

  ranger-admin:
    image: ghcr.io/takezoe/ranger-docker/ranger-admin:v2.4.0
    # build:
    #   context: ./ranger-admin
    #   dockerfile: Dockerfile
    container_name: ranger-admin
    ports:
      - 6080:6080
    depends_on:
      - ranger-mysql
      - ranger-solr

  ranger-mysql:
    image: mysql:8.0.33
    container_name: ranger-mysql
    ports:
      - 3306:3306
    volumes:
      - ./ranger-mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rangeradmin
      MYSQL_PASSWORD: rangeradmin
      MYSQL_DATABASE: ranger

  ranger-solr:
    image: solr:8.11.2
    container_name: ranger-solr
    ports:
      - 8983:8983
    volumes:
      - ./ranger-solr:/opt/solr/server/solr/configsets/ranger_audits/conf
    entrypoint:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits
