version: '2'

services:
  ranger-admin:
    image: ranger-admin
    ports:
    - 6080:6080
    depends_on:
    - ranger-mysql
    - ranger-solr
  ranger-mysql:
    image: mysql:8.0.21
    ports:
    - 3306:3306
    volumes:
    - ./ranger-mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rangeradmin
      MYSQL_PASSWORD: rangeradmin
      MYSQL_DATABASE: ranger
  ranger-solr:
    image: solr:8
    ports:
    - 8983:8983
    volumes:
    - ./ranger-solr:/opt/solr/server/solr/configsets/ranger_audits/conf
    entrypoint:
    - solr-precreate
    - ranger_audits
    - /opt/solr/server/solr/configsets/ranger_audits
